version: '3.7'
services:
  db:
    expose:
      - 5432
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
  web:
    expose:
      - 8000
    environment:
      DJANGO_MANAGEPY_MIGRATE: "on"
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/mysite/
      - /static/
      - /template/
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  postgres_data: